### PR TITLE
Interactive Image Component

### PR DESCRIPTION
**Pull request by joeyleesi**
Allows for adding images with buttons to display further information

## Usage

```jsx
import InfoImage from '@site/src/components/InteractiveImage/Image';
import InfoImageButton from '@site/src/components/InteractiveImage/Button';

<InfoImage
  url={require('@site/static/img/figuraMenu.png').default}
  width='800px'
  height='450px'
>
  <InfoImageButton
    id='new' // unique id for the button
    left='71px' // how many pixels from the left edge of parent image
    top='47px' // how many pixels from the top edge of parent image
    width='30px' // width in pixels
    height='30px' // height in pixels
  >
    hello
  </InfoImageButton>
  <InfoImageButton
    id='square'
    left='105px'
    top='47px'
    width='30px'
    height='30px'
    debug // render a red border on the button
  >
    hello2
  </InfoImageButton>
  <InfoImageButton
    id='folder'
    left='139px'
    top='47px'
    width='30px'
    height='30px'
    style={{width: '300px', top: '80px', left: '139px', position: 'absolute'}} // css styling for the div that is parent to the children of this component (used in this example to move the markdown note)
  >

:::note

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::

  </InfoImageButton>
</InfoImage>
```

## Things to note
- Markdown within a component can not be indented (see the folder example)
- Markdown must have a blank line above and below (see the folder example)
- mdx can't be indented with 4 spaces or else it will be interpreted as a code block
- id must be unique
- debug prop can be added to render a red border to make it easier to place the button (see square example)

## example video

https://github.com/FiguraMC/wiki/assets/98718890/98f921ad-e621-475a-81c1-13146184bed4

### CODE REVIEW

**Comment by skyrina** [comment]
maybe add a toggle for an animation that slowly fades a transparent white overlay in and out even if they aren't selected? that way people will be able to easily see what's clickable and what isn't.

**Comment by joeyleesi** [comment]
Hows this look? The animation can be toggled on by passing `pulse` prop

https://github.com/FiguraMC/wiki/assets/98718890/6cda546f-b4c5-4778-bb9b-a61003acf847

**Comment by joeyleesi** [comment]
Oh I forgot to mention, I removed the debug option since you can use the animation to place the buttons

**Comment by skyrina** [comment]
it looks good! but, would it be possible to make them pulse at the same time?

**Comment by joeyleesi** [comment]
oki fixed that! the solution might be a bit hacky lol but I wasn't sure of a better way  to do it

**Comment by skyrina** [comment]
that looks great! thank you

**Pull request merged**
